const {criarQuestao,listarQuestoes,buscarQuestaoPorId, buscarIdPorNome, atualizarQuestao,excluirQuestao,buscarquestoesDisponiveis} = require('../controllers/questionarioController');
const questionarioRouter = require('express').Router();
questionarioRouter.post('/questoes', criarQuestao);
questionarioRouter.get('/questoes', listarQuestoes);
questionarioRouter.get('/questoes/disponivel', buscarquestoesDisponiveis);
questionarioRouter.get('/questoes/:id', buscarQuestaoPorId);
questionarioRouter.get('/questoes/:titulo', buscarIdPorNome);
questionarioRouter.put('/questoes/:id', atualizarQuestao); 
questionarioRouter.delete('/questoes/:id', excluirQuestao);
module.exports = questionarioRouter;
